I am attempting to send an event from my salt-minion to my salt-master, which seemed to work perfectly fine on linux now that I am trying the same thing with OS X it fails with a traceback although the event actually reaches the server.

_Update:_ It seems to happen with any module.run state

Heres the traceback after running the sls file on the minion

```
      ID: test
Function: module.run
    Name: event.fire_master
  Result: False
 Comment: An exception occurred in this state: Traceback (most recent call last):
            File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1382, in call
              **cdata['kwargs'])
            File "/usr/local/lib/python2.7/site-packages/salt/states/module.py", line 203, in run
              if ret['changes'].get('ret', {}).get('retcode', 0) != 0:
          AttributeError: 'bool' object has no attribute 'get'
 Changes:
```

Here's what I had in my sls file

```
 test:
  module.run:
    - name: event.fire_master
    - tag: 'moo'
    - data: '{test: "two"}'
```

And here's the event reaching the salt-master

```
Event fired at Tue Oct 21 11:38:26 2014
*************************
Tag: moo
Data:
{'_stamp': '2014-10-21T11:38:26.019078',
 'cmd': '_minion_event',
 'data': '{test: "two"}',
 'id': 'buildusers-Mac.local',
 'pretag': None,
 'tag': 'moo'}
```

Salt version info

```
           Salt: 2014.1.13
         Python: 2.7.8 (default, Oct 19 2014, 16:03:53)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.11
          PyZMQ: 14.4.0
            ZMQ: 4.0.5
```
