I have setup s3fs with the following configuration settings:

```
fileserver_backend:
  - roots
  - s3fs

s3.keyid: <keyid>
s3.key: <key>
s3.location: us-east-1

s3.buckets:
  - ch3lltests
```

Due to another bug I included the following PR into the salt code on my box: https://github.com/saltstack/salt/pull/28535

When I run `salt '*' s3.get` I am receiving the following error:

```
[root@localhost utils]# salt '*' s3.get                                                                                                                        
45.79.69.188:
    |_
      ----------
      Code:
          AuthorizationHeaderMalformed
    |_
      ----------
      Message:
          The authorization header is malformed; a non-empty region must be provided in the credential.
    |_
      ----------
      RequestId:
          <requestidnumber>
    |_
      ----------
      HostId:
          <hostidnumber>
```

Here is my debug logs:

```
2015-11-03 22:50:18,717 [salt.utils.lazy  ][DEBUG   ][27423] LazyLoaded local_cache.prep_jid
2015-11-03 22:50:18,717 [salt.utils.event ][DEBUG   ][27423] Sending event - data = {'_stamp': '2015-11-03T22:50:18.717288', 'minions': ['45.79.69.188']}
2015-11-03 22:50:18,718 [salt.utils.event ][DEBUG   ][27423] Sending event - data = {'tgt_type': 'glob', 'jid': '20151103225018716911', 'tgt': '*', '_stamp': '2015-11-03T22:50:18.717732', 'user': 'root', 'arg': [], 'fun': 's3.get', 'minions': ['45.79.69.188']}
2015-11-03 22:50:18,718 [salt.master      ][INFO    ][27423] User root Published command s3.get with jid 20151103225018716911
2015-11-03 22:50:18,719 [salt.master      ][DEBUG   ][27423] Published command details {'tgt_type': 'glob', 'jid': '20151103225018716911', 'tgt': '*', 'ret': '', 'user': 'root', 'arg': [], 'fun': 's3.get'}
2015-11-03 22:50:22,222 [salt.utils.job   ][INFO    ][27437] Got return from 45.79.69.188 for job 20151103225018716911
2015-11-03 22:50:22,222 [salt.utils.event ][DEBUG   ][27437] Sending event - data = {'fun_args': [], 'jid': '20151103225018716911', 'return': [{'Code': 'AuthorizationHeaderMalformed'}, {'Message': 'The authorization header is malformed; a non-empty region must be provided in the credential.'}, {'RequestId': '<requestidnumber'}, {'HostId': '<hostidnumber>'}], 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2015-11-03T22:50:22.222266', 'fun': 's3.get', 'id': '45.79.69.188'}
2015-11-03 22:50:27,092 [salt.config      ][DEBUG   ][27414] Reading configuration from /etc/salt/master
2015-11-03 22:50:27,155 [salt.config      ][DEBUG   ][27414] Including configuration from '/etc/salt/minion.d/_schedule.conf'
2015-11-03 22:50:27,155 [salt.config      ][DEBUG   ][27414] Reading configuration from /etc/salt/minion.d/_schedule.conf
2015-11-03 22:50:27,157 [salt.config      ][DEBUG   ][27414] Using cached minion ID from /etc/salt/minion_id: 45.79.69.188
2015-11-03 22:50:27,158 [salt.config      ][DEBUG   ][27414] Reading configuration from /etc/salt/master
2015-11-03 22:50:27,957 [salt.utils.lazy  ][DEBUG   ][27414] LazyLoaded local_cache.clean_old_jobs
2015-11-03 22:50:27,962 [salt.utils.lazy  ][DEBUG   ][27414] Could not LazyLoad config.merge
2015-11-03 22:50:27,962 [salt.fileserver  ][DEBUG   ][27414] Updating roots fileserver cache
2015-11-03 22:50:27,962 [salt.fileserver  ][DEBUG   ][27414] Updating s3fs fileserver cache
2015-11-03 22:50:27,963 [salt.loaded.int.fileserver.s3fs][DEBUG   ][27414] Refreshing buckets cache file
2015-11-03 22:50:27,963 [salt.utils.aws   ][INFO    ][27414] us-east-1
2015-11-03 22:50:27,963 [salt.utils.aws   ][INFO    ][27414] us-east-1
2015-11-03 22:50:27,963 [salt.utils.aws   ][INFO    ][27414] us-east-1
2015-11-03 22:50:27,964 [salt.utils.s3    ][DEBUG   ][27414] S3 Request: https://ch3lltests.s3.amazonaws.com/?
2015-11-03 22:50:27,964 [salt.utils.s3    ][DEBUG   ][27414] S3 Headers::
2015-11-03 22:50:27,964 [salt.utils.s3    ][DEBUG   ][27414]     Authorization:<auth information> [requests.packages.urllib3.connectionpool][INFO    ][27414] Starting new HTTPS connection (1): ch3lltests.s3.amazonaws.com
2015-11-03 22:50:28,298 [requests.packages.urllib3.connectionpool][DEBUG   ][27414] "GET / HTTP/1.1" 200 None
2015-11-03 22:50:28,301 [salt.utils.s3    ][DEBUG   ][27414] S3 Response Status Code: 200
2015-11-03 22:50:28,302 [salt.loaded.int.fileserver.s3fs][DEBUG   ][27414] Writing buckets cache file
2015-11-03 22:50:28,302 [salt.loaded.int.fileserver.s3fs][INFO    ][27414] Syncing local cache from S3...
2015-11-03 22:50:28,302 [salt.loaded.int.fileserver.s3fs][INFO    ][27414] ch3lltests -  : test
2015-11-03 22:50:28,303 [salt.loaded.int.fileserver.s3fs][INFO    ][27414] Sync local cache from S3 completed.
2015-11-03 22:50:28,303 [salt.utils.verify][DEBUG   ][27414] This salt-master instance has accepted 1 minion keys.
```

Here is my salt versions report:

```
[root@localhost utils]# salt --versions-report                                                                                                                 
Salt Version:
           Salt: 2015.8.1

Dependency Versions:
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
           RAET: Not Installed
        Tornado: 4.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: centos 7.0.1406 Core
        machine: x86_64
        release: 4.1.5-x86_64-linode61
         system: CentOS Linux 7.0.1406 Core
```
