### Description of Issue
Trying to download files via ftp. Does not work. 
Using http(s) works fine. 

### Steps to Reproduce Issue
Not working
```
salt '*' cp.get_url ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/amd64/12.0-RELEASE/MANIFEST /tmp/MANIFEST
```

Works 
```
salt '*' cp.get_url https://download.freebsd.org/ftp/releases/amd64/amd64/12.0-RELEASE/MANIFEST /tmp/MANIFEST
```
#### Error 

```
salt '*' cp.get_url ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/amd64/12.0-RELEASE/MANIFEST /tmp/MANIFEST
[WARNING ] /usr/local/lib/python3.6/site-packages/salt/transport/ipc.py:292: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  self.unpacker = msgpack.Unpacker(encoding=encoding)

[WARNING ] /usr/local/lib/python3.6/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

testminion:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/salt/fileclient.py", line 540, in get_url
        ftp.connect(url_data.hostname, url_data.port)
      File "/usr/local/lib/python3.6/ftplib.py", line 145, in connect
        if port > 0:
    TypeError: '>' not supported between instances of 'NoneType' and 'int'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/local/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/salt/modules/cp.py", line 418, in get_url
        path, dest, makedirs, saltenv, source_hash=source_hash)
      File "/usr/local/lib/python3.6/site-packages/salt/fileclient.py", line 548, in get_url
        raise MinionError('Could not retrieve {0} from FTP server. Exception: {1}'.format(url, exc))
    salt.exceptions.MinionError: Could not retrieve ftp://ftp.freebsd.org/pub/FreeBSD/releases/amd64/amd64/12.0-RELEASE/MANIFEST from FTP server. Exception: '>' not supported between instances of 'NoneType' and 'int'
ERROR: Minions returned with non-zero exit code
```


### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Aug 22 2019, 01:16:05)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: US-ASCII
        machine: amd64
        release: 12.0-RELEASE-p10
         system: FreeBSD
        version: Not Installed
```

I also tried this with file.managed , but the results are the same. Can anyone verify this ? 
